#!/usr/bin/env python3
"""
assign_active_keys.py — apply active_key_map.json to a seeded ingredients.db,
emitting active_key_updates.sql for `turso db shell vials-corpus`.

Usage:
    python3 assign_active_keys.py <ingredients.db> <active_key_map.json> [outdir]

Two signals, in priority order (per DATA_PIPELINE.md):
  1. Annex VI membership -> 'spf_filters' (EU's own legal UV-filter list, authoritative,
     catches filters a name-regex would miss).
  2. Exact match of inci_name_norm or any synonym against active_key_map.json.

Note: this re-applies the delivered name->key vocabulary; it does not regenerate that
vocabulary from scratch (the original per-class pattern classifier was not checked into
handoff/, only its active_key_map.json output was).
"""
import json, sqlite3, sys
from pathlib import Path

def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    dbp, mapp = Path(sys.argv[1]), Path(sys.argv[2])
    outdir = Path(sys.argv[3] if len(sys.argv) > 3 else dbp.parent); outdir.mkdir(exist_ok=True)
    kmap = json.load(open(mapp, encoding="utf-8"))

    db = sqlite3.connect(dbp); db.row_factory = sqlite3.Row
    rows = db.execute("SELECT uid, inci_name_norm, synonyms, annexes FROM ingredients").fetchall()

    updates, counts = [], {}
    for r in rows:
        annexes = json.loads(r["annexes"])
        if "VI" in annexes:
            key = "spf_filters"
        else:
            key = kmap.get(r["inci_name_norm"])
            if key is None:
                for syn in json.loads(r["synonyms"]):
                    key = kmap.get(syn.lower())
                    if key:
                        break
        if key:
            updates.append((r["uid"], key))
            counts[key] = counts.get(key, 0) + 1

    with open(outdir / "active_key_updates.sql", "w", encoding="utf-8") as f:
        f.write("-- active_key assignment (annex VI -> spf_filters, else active_key_map.json) "
                "— generated by assign_active_keys.py\n")
        f.write("BEGIN;\n")
        for uid, key in updates:
            f.write(f"UPDATE ingredients SET active_key = '{key}' WHERE uid = '{uid}';\n")
        f.write("COMMIT;\n")

    print(f"assigned active_key to {len(updates)} / {len(rows)} ingredients")
    print("per key:", dict(sorted(counts.items(), key=lambda kv: -kv[1])))
    print(f"wrote {outdir / 'active_key_updates.sql'}")

if __name__ == "__main__":
    main()
